name = "Enhanced Vanilla (FO)"
author = "Minegame Ytb"
version = "1.0.3-1.20.1-RELEASE"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ee8c7d7dbdb9cdf18bc0a59c2473a77cb1d1c84865b8426f388ff95280189e"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
