name = "Enhanced Vanilla (FO)"
author = "Minegame Ytb"
version = "1.0.3-1.20.1-RELEASE"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "523c9b9ba106f7890b5f035626a11e5052c77b4c816fd4cf22f5c5d8b3b44123"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
