name = "Enhanced Vanilla (FO)"
author = "Minegame Ytb"
version = "1.0.3-1.20.1-RELEASE"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2e6a0c5f482e821471c3809f68cb5b7f0bf9d35e2ebec8651f38a61f77b7370"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
